theme: jekyll-theme-minimal
title: Brice Le Borgne
description: datajournalisme & enquête en sources ouvertes 
      </br>
      </br>
      </br>
      <h3>Contact</h3>
      <ul>
        <li>en DM sur <a href="http://www.twitter.com/BriceLeBorgne">Twitter</a></li>
        <li>brice.leborgne@protonmail.com - <a href="/files/publickey.brice.leborgne@protonmail.com.asc">ma clé PGP publique est ici</a></li>
        <li>par messagerie chiffrée (Signal ou Telegram)</li>
      </ul>


